### ISSUE TITLE
02.Complete inbound

### ISSUE THREAD

**Issue by nanda32** [astpl1998/logistics#10]
[02. PC_WMS_MIS Report_0008_Complete Transaction Report - Inbound_V 1 0.xlsx](https://github.com/astpl3/logistics/files/1855738/02.PC_WMS_MIS.Report_0008_Complete.Transaction.Report.-.Inbound_V.1.0.xlsx)

**Comment by parthiban25** [comment]
[2.PC_WMS_MIS Report_0008_Complete Transaction Report - Inbound_V 1 0.xlsx](https://github.com/murugananthaml/logistics/files/1906156/2.PC_WMS_MIS.Report_0008_Complete.Transaction.Report.-.Inbound_V.1.0.xlsx)
Testing is completed

**Comment by parthiban25** [comment]
Pending in Launch screen only

**Comment by parthiban25** [comment]
[inbound issue as on 24-4-2018.xlsx](https://github.com/murugananthaml/logistics/files/1941519/inbound.issue.as.on.24-4-2018.xlsx)
Testing issue inbound order 
landing screen i and table issue .kindly resolve the issue

**Comment by parthiban25** [comment]
Dear Devi,
Here attached for inbound order screen shot print
[Inbound order screen shot.xlsx](https://github.com/murugananthaml/logistics/files/1953929/Inbound.order.screen.shot.xlsx)
Regards
parthiban.R

**Comment by DeviAmitysoft** [comment]
Inbound issues are complted ,Kindly check and revert.

**Comment by parthiban25** [comment]
Dear Devi,
1.Landing screen issues (primary ref. Doc .No --->"ALL" Option can be added)

Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
Dear  Devi,
Testing issues 
Pending points 
1.landing screen sign symbol came that is not Required
2.landing screen add primary ref.no. "ALL"option is required
Here attached screen shot for reference
Transaction No:
primary ref.doc.no: prcon0007
[Inbound01.xlsx](https://github.com/murugananthaml/logistics/files/1966975/Inbound01.xlsx)

**Comment by parthiban25** [comment]
Dear Devi,
 Testing issues
 Pending points
 1.landing screen sign symbol came that is not Required
 2.landing screen add primary ref.no. "ALL" option is required
3.Landing screen Date  "from to" field is Mandatory . If Date range is Exceed system throw error in Base Screen
 Here attached screen shot for reference
 Transaction No:
 primary ref.doc.no: prcon0007
[Inbound01.xlsx](https://github.com/murugananthaml/logistics/files/1967083/Inbound01.xlsx)

**Comment by parthiban25** [comment]
Dear Devi,
Below fields are fetching blank for given primary ref doc no and this has all the below information
Primary Ref doc no - 20180529PROD01oi00
Gate In date and time 
Gate out date and time 
Vehicle no 
Transporter name
Stock status 
[inbound order as on 29-5-2018.xlsx](https://github.com/murugananthaml/logistics/files/2048511/inbound.order.as.on.29-5-2018.xlsx)

Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi Devi,
inbound order -->correction
Gate inDate  & Time-->Goto ASN Screen Take "Gate pass no " or "ASN Primary Ref.no"or "ASN.No".then make Goto Gate operation screen "above mention 3 Ref.any satisfied .put Display  the Gate in Date & Time" Display "
Gate Out Date and Time-->same logic for above mention
vehicle no-->same logic for above mention
Transporter name-->same logic for above mention
thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi,

Inbound & Outbound Delivered in Live Server
front end and Back end Object & Sp 
kindly refer the attached
[INBOUND_OUTBOUND.zip](https://github.com/astpl1998/logistics/files/2620019/INBOUND_OUTBOUND.zip)

Thanks & Regards
Parthiban.R

**Comment by raju-kurup** [comment]
Development completed
