### ISSUE TITLE
03.Complete outbound

### ISSUE THREAD

**Issue by nanda32** [astpl1998/logistics#11]
[03.PC_WMS_MIS Report_0009_Complete Transaction Report Outbound_V 1 0.xlsx](https://github.com/astpl3/logistics/files/1855739/03.PC_WMS_MIS.Report_0009_Complete.Transaction.Report.Outbound_V.1.0.xlsx)

**Comment by murugeshkumar-T** [comment]
Need functional clarity and sample data for 10 columns in outbound report.

**Comment by parthiban25** [comment]
As  already intimate we cannot proceed the  full cycle .As logic  already explained .kindly completed the report .

**Comment by murugeshkumar-T** [comment]
without the data i con't able to find the table , we con't able to move further.

**Comment by parthiban25** [comment]
As i Discuss with Skype and Phone communication we can clarified the 10 Field .Kindly completed the Report.

**Comment by parthiban25** [comment]
[outbound order error.xlsx](https://github.com/murugananthaml/logistics/files/1906165/outbound.order.error.xlsx)
Testing completed

**Comment by parthiban25** [comment]
Testing issues for outbound  order
[3.PC_WMS_MIS Report_0009_Complete Transaction Report Outbound_V 1 0.xlsx](https://github.com/murugananthaml/logistics/files/1923437/3.PC_WMS_MIS.Report_0009_Complete.Transaction.Report.Outbound_V.1.0.xlsx)
Yellow line are mark the issues. kindly solve the issue

**Comment by murugeshkumar-T** [comment]
[outbound.xlsx](https://github.com/murugananthaml/logistics/files/1931096/outbound.xlsx)
 i have completed mentioned issues and updated the attached file

**Comment by parthiban25** [comment]
[outbound issue as on 24-4-2018.xlsx](https://github.com/murugananthaml/logistics/files/1942337/outbound.issue.as.on.24-4-2018.xlsx)
testing issue for outbound order report .kindly resolve issue it Needful

Thanks 
parthiban.R

**Comment by parthiban25** [comment]
Dear Murugantham,
Outbound order Report Launched should be as error
Empty searched filter option not working
[Outbound order error.xlsx](https://github.com/murugananthaml/logistics/files/1953957/Outbound.order.error.xlsx)

Landing screen option also not working
here attached report screen shot

**Comment by parthiban25** [comment]
Dear Team
Ramco Testing issues as on 27-4-2018
Complete Outbound Transaction 

1.	On selection of the report name, I get ~#~ signs, in few of the fields .PFA the screenshot. 
2.	Fetches the report only if the Primary Ref Doc Type is STO and not for SO,  though data is there.  Also, please add ‘ALL’ in Primary Ref Doc Type, so that user can view all the Primary Ref doc’s in one report.
3.	Date From and Date To is not vanishing, I have to manually remove it, while toggling between the Reports in Select Report.

**Comment by murugeshkumar-T** [comment]
in outbound order point no 2 is completed 
point  no 1,3 we made changes in design, once deploy the latest object issue resolved.

**Comment by parthiban25** [comment]
Dear murugeshkumar

Kindly completed the testing point outbound order
Thanks & Regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
except all option ,remailing issue is resolved

**Comment by murugeshkumar-T** [comment]
all option is completed in outbound report

**Comment by parthiban25** [comment]
hi Devi,
@outbound order -->additional requirement-->Wave time, pick time, pack time, Gate in, Gate Out time is fetching only Hours, mins and no secs.  Format is like "03:55: " requesting to add secs.
kindly Resolved this issues

thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
hi Devi,
@outbound order-->correction section is clear .But Required Sec in 2 Decimal only
Ex:"03:55:45"like this only
Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
Outbound order,
Please find the below screen shot . Courier / Transport is fetching blank in the report.  I have provide in my gate details.
Criteria
Customer - P023
Location ID - TN001-P023
Date from and To – 08/06/18 to 08/06/18

[outbound order testing.xlsx](https://github.com/murugananthaml/logistics/files/2119339/outbound.order.testing.xlsx)
thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

Inbound & Outbound Delivered in Live Server
front end and Back end Object & Sp 
kindly refer the attached


[INBOUND_OUTBOUND.zip](https://github.com/astpl1998/logistics/files/2620025/INBOUND_OUTBOUND.zip)


Thanks & Regards
parthiban.R

**Comment by raju-kurup** [comment]
Development completed
