### ISSUE TITLE
04.Vehicle Dock-in

### ISSUE THREAD

**Issue by nanda32** [astpl1998/logistics#12]
[04.PC_WMS_MIS_Report_0002_Vehicle Dock in-out Report_V 1 0.xlsx](https://github.com/astpl3/logistics/files/1855741/04.PC_WMS_MIS_Report_0002_Vehicle.Dock.in-out.Report_V.1.0.xlsx)

**Comment by murugananthaml** [comment]
IEDK design details

Component Name : LGT_Reports
Activity  Name         : vehical_in_out_repor
Ilbo Name                 : Dock_in_report

**Comment by DeviAmitysoft** [comment]
Dear Parthiban,
I have completed dock in out report,only division logic is pending,for that need input.

**Comment by DeviAmitysoft** [comment]
Dear Parthiban,
I have completed dock in out report,only division logic is pending,for that need input.

**Comment by parthiban25** [comment]
Dear Devi,
Kindly Resolve the issue
Herewith attached for Excel Format
[Docket In And Out.xlsx](https://github.com/murugananthaml/logistics/files/1970152/Docket.In.And.Out.xlsx)
Thanks & Regards
Parthiban.R

**Comment by DeviAmitysoft** [comment]
everything got completed in dock in Report,Only the sizes of the screen not yet completed,please check other things and revert.

**Comment by parthiban25** [comment]
hi,
Ramco logged the issue as on 12-6-2018

[Dock report.xlsx](https://github.com/murugananthaml/logistics/files/2092670/Dock.report.xlsx)

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi Devi ,
Dock to stock report Defect 
Please find the below screen shot.
DOCK in and DOCK out time is fetching blank.

[Dock to stock.xlsx](https://github.com/murugananthaml/logistics/files/2119267/Dock.to.stock.xlsx)

Thanks & Regards
Parthiban.R

**Comment by DeviAmitysoft** [comment]
Hi,
  Parthiban
  Defect resolved,Kindly check and revert.

**Comment by parthiban25** [comment]
hi,
Kindly resolved the issue
Dock to stock Report

[Dock to stock22.xlsx](https://github.com/murugananthaml/logistics/files/2129686/Dock.to.stock22.xlsx)


thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

Dock in & OUT  Delivered in Live Server
front end and Back end Object & Sp 
kindly refer the attached
[GATE DOC IN OUT.zip](https://github.com/astpl1998/logistics/files/2620038/GATE.DOC.IN.OUT.zip)


Thanks & Regards

Parthiban.R

**Comment by raju-kurup** [comment]
Development completed
