### ISSUE TITLE
05.Vehicle-Gate in - out

### ISSUE THREAD

**Issue by nanda32** [astpl1998/logistics#13]
[05.PC_WMS_MIS_Report_0003_Vehicle Gate in-out Report_V 1 0.xlsx](https://github.com/astpl3/logistics/files/1855743/05.PC_WMS_MIS_Report_0003_Vehicle.Gate.in-out.Report_V.1.0.xlsx)

**Comment by murugananthaml** [comment]
IEDK design details 😄 
Component Name          : LGT_Reports
Activity Name                    : veh_in_out_rpt
ILBO Name                         : veh_mov_rpt

**Comment by parthiban25** [comment]
Dear murugeshkumar,
Kindly update the status for Vehicle In & Out Report 
Thanks & Regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
Dear parthiban,
Vehicle in & out report is completed in proconnect server.
if have any further modification kindly let me know.

**Comment by nanda32** [comment]
Issue logged by ramco on 25-05-2018
When I fetch the report in Excel, after 22 lines, I get the logo, heading again/ Please remove it and give it as a continuous excel report. 
I had created a Gate In an Gate Out today, for the location , when trying to Print the report, I get “There is no data for the given input”
Please rectify and confirm.
![excel report](https://user-images.githubusercontent.com/37866185/40541216-8185bcf0-6038-11e8-8863-32eb4b4ccaec.png)
![gate 2](https://user-images.githubusercontent.com/37866185/40541218-81c05c20-6038-11e8-84e9-9ad7f19d5f44.png)
![vehicle gate in and out](https://user-images.githubusercontent.com/37866185/40541225-8d757b7c-6038-11e8-84cc-af0c11289fd7.png)

**Comment by murugeshkumar-T** [comment]
Dear nandha, 
1) page issue is resolved in  proconnedt uat server. 
2) no data issue, input is not a valid input  
ex: gate execution customer is :  'Redington India'   this description is not available in customer master,
once provide the exact customer name on gate execution it will launch

**Comment by parthiban25** [comment]
Dear Devi,
Vehicle Gate in/out Report
Testing Defect changes 
[5.PC_WMS_MIS_Report_0003_Vehicle Gate in-out Report_V 1 0.xlsx](https://github.com/murugananthaml/logistics/files/2058115/5.PC_WMS_MIS_Report_0003_Vehicle.Gate.in-out.Report_V.1.0.xlsx)

Thanks & Regards
parthiban.R

**Comment by DeviAmitysoft** [comment]
Dear Parthiban,
                i need to complete Vehicle_Turn_Around_Time in vehicle gate in out report.

**Comment by DeviAmitysoft** [comment]
Dear Parthiban,
                     I have completed vehicle dock in out report,Kindly check and revert.

**Comment by murugeshkumar-T** [comment]
[Proconnect objects on 15-10-2018.zip](https://github.com/astpl1998/logistics/files/2571260/Proconnect.objects.on.15-10-2018.zip)

**Comment by parthiban25** [comment]
hi,

Dock in & OUT Delivered in Live Server
front end and Back end Object & Sp
kindly refer the attached
[GATE DOC IN OUT.zip](https://github.com/astpl1998/logistics/files/2620046/GATE.DOC.IN.OUT.zip)


Thanks & Regards

Parthiban.R

**Comment by raju-kurup** [comment]
Development completed
