### ISSUE TITLE
07.ASN Format

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#16]
ASN   Format
--

**Comment by parthiban25** [comment]
[7.Dvert_WMS_O0004_ASN Format_V1 0.xlsx](https://github.com/murugananthaml/logistics/files/1878872/7.Dvert_WMS_O0004_ASN.Format_V1.0.xlsx)

**Comment by nanda32** [comment]
[ASN FORMAT - TESTING - 24-04-2018.xlsx](https://github.com/murugananthaml/logistics/files/1942077/ASN.FORMAT.-.TESTING.-.24-04-2018.xlsx)
@murugeshkumar-T pls resolve the testing issues

**Comment by parthiban25** [comment]
[ASN Format.xlsx](https://github.com/murugananthaml/logistics/files/1942391/ASN.Format.xlsx)
print is Generated but Data is not fetched the Report.
 UAT server
https://vert.ramcouat.com/rvw/
 user name:wmuser
 password:wmuser18

Thanks
 parthiban.R

**Comment by parthiban25** [comment]
ASN Format testing issue is  completed
pending
1.Logo Pending
2.Report launching In same screen print
Regards
parthiban.R

**Comment by parthiban25** [comment]
Dear Devi,
Kindly completed the ASN Format Today
Below pending points
1.Logo
2.There are two Print in ASN Format But one is completed and another link print is pending
3.attached Notes pending
Regards
parthiban.R

**Comment by parthiban25** [comment]
Dear Devi,

ASN Format completed

Thanks & Regards
parthiban.R

**Comment by raju-kurup** [comment]
Development completed
