### ISSUE TITLE
08.Dvert Alert -incoming  SKU

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#17]
Dear Murugantham,

New Requirement for Dvert alert-Incoming Skus
Here with attached PFS for your Reference
[8.ANWMS033_Dvert_Incoming SKU Alert as on 3-5-2018.docx](https://github.com/murugananthaml/logistics/files/1969681/8.ANWMS033_Dvert_Incoming.SKU.Alert.as.on.3-5-2018.docx)

Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
Dear Murugantham,

Sample Data is created in Unloded Screen kindly check

[unloaded issues is resolve.xlsx](https://github.com/murugananthaml/logistics/files/2000779/unloaded.issues.is.resolve.xlsx)


Thank & Regards
Parthiban.R

**Comment by murugananthaml** [comment]
as discussed kindly create Employee Group=Warehouse Manager/Operations Supervisor/ Receiving Office Operator/Dock Receiver

**Comment by parthiban25** [comment]
Dear Murugantham,

I will created in Development server  in  Employee Group=Warehouse Manager/Operations Supervisor/ Receiving Office Operator/Dock Receiver.Kindly check the server
URl:http://172.16.18.58/RVW/extui/vwrt/LaunchPanel.htm

thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
Hi,
1.ASN Confirmation --->Testing issues are attached in Excel
[ASN CON01.xlsx](https://github.com/murugananthaml/logistics/files/2030765/ASN.CON01.xlsx)


2.unloading-->Testing issues are attached in excel 
[unloading trigger.xlsx](https://github.com/murugananthaml/logistics/files/2030768/unloading.trigger.xlsx)
There are 2 group send to alert one alert is working and another person alert not working.kindly resolve the issue
Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
Dear murugantham,
Please check – Incoming SKU alert not triggered for ASN000000498 & Inventory 

Thanks&regards
parthiban.R

**Comment by parthiban25** [comment]
hi

Alert not working in UAT Server
income skus		
			
1	ASN000000486		Not working
			
2	ULPLN000000041		Not working
			
3	ULPLN000000042		Not working


Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi murugantham,
Ramco has been raise the Defect  as on 27-6-2018
ASN Income SKUs
1.Excel format is not proper
2.seller  id is fetching the item ID
3.item Description is also fetching the item id
4.reason code is hard coded as new seller/new  item
5.Expected time format is not correct
6.Email format is not correct
7.ASN000000598 has mixed SKU but it doesn't show up in the alert excel
8.alert not triggered when damaged items are received in GRPLN000000367

Thanks & Regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
[RAMCO INCOMMING SKU.zip](https://github.com/astpl1998/logistics/files/2627983/RAMCO.INCOMMING.SKU.zip)

**Comment by raju-kurup** [comment]
Development completed
