### ISSUE TITLE
09.Dvert -Order aged between 24 and 48 hours

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#18]
Dear Murugantham,

New Requirement for Dvert -Order aging Report
 Here with attached PFS for your Reference
PFB rtrack ID raised for Dvert MIS Report – Orders aged between 24 and 48 hours. This report also covers 2 other Reports,
Dvert_WMS_M0007	       Orders aged between 24 and 48 hrs
Dvert_WMS_M0008 	Orders aged >48 hrs
Dvert_WMS_M0009	     Oldest Aged Order
[9.Dvert_WMS_M0007_Orders aged between 24 to 48 hours_V1 0 3-5-2018.xlsx](https://github.com/murugananthaml/logistics/files/1969685/9.Dvert_WMS_M0007_Orders.aged.between.24.to.48.hours_V1.0.3-5-2018.xlsx)
Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
rTrack ID: EPE-6730

**Comment by parthiban25** [comment]
Dear Devi,
 Ramco has some changes is happen in PFS .So Modification PFS Use this. Herewith attached for you Reference.

**Comment by parthiban25** [comment]
Dear Devi,
 Ramco has some changes is happen in PFS .So Modification PFS Use this. Herewith attached for you Reference.
[9. Dvert_WMS_M0007_Orders aged between 24 to 48 hours_V1 0 as on 4-5-2018.xlsx](https://github.com/murugananthaml/logistics/files/1973298/9.Dvert_WMS_M0007_Orders.aged.between.24.to.48.hours_V1.0.as.on.4-5-2018.xlsx)


Thanks & Regards
Parthiban.R

**Comment by DeviAmitysoft** [comment]
Dear Parthiban ,
                need data to fetch Outbound Order Status,Reason Code,Status,Reason Code,Unit Status,Reason Code columns and also need clarification on logics,Kindly clarify.

**Comment by parthiban25** [comment]
Dear Devi,

Pending logics are Given .kindly completed the Report

Thanks & Regards
parthiban.R

**Comment by DeviAmitysoft** [comment]
Dear parthiban,
                    I have completed report on vert test server,Kindly check and revert.

**Comment by nanda32** [comment]
Pls 
[order aged.xlsx](https://github.com/murugananthaml/logistics/files/2013358/order.aged.xlsx)
Pls find the testing issues

**Comment by DeviAmitysoft** [comment]
I have completed the status and reasoncode column ,Kindly check and revert.

**Comment by nanda32** [comment]
[Order aged between 24 and 48 hours -Ver1.0.xlsx](https://github.com/murugananthaml/logistics/files/2025197/Order.aged.between.24.and.48.hours.-Ver1.0.xlsx)

Devi:Pls find the testing issues in landing screen

**Comment by nanda32** [comment]
Only 1 record is coming for status all.

**Comment by parthiban25** [comment]
hi,
kindly resolved issues

Only 1 record is coming for status all. (Refer attachment – Screenshot(78), Screenshot(79))

![order aging](https://user-images.githubusercontent.com/37869674/41098230-3417044e-6a4a-11e8-9f01-fe1d663249a8.png)

Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
ARI  Report Error in UAT Server
Order Aging Report
Orders aged between 24 and 48 hrs	VDT-199 (Fix Reject) no data is coming up
Orders aged >48 hrs 	                         VDT-199 (Fix Reject) no data is coming up
Oldest Aged Order	                                  VDT-199 (Fix Reject) no data is coming up

Thanks & Regards
parthiban.R

**Comment by DeviAmitysoft** [comment]
Hi,
   Kindly provide test data for Order Aging Report.


  Regards
  Devi
  Amitysoft.

**Comment by parthiban25** [comment]
hi,
kindly changed the title: "order Aging " align as center
Report launched throw error .kindly resolved the issue

Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi Devi
ramco issue logged as on 27-6-2018
1. Closed orders are coming in orders aged report. For example - ODO000003881 & ODO000003883. 
2. Outbound Order Date Format should be in US format. 
3. Unit Number is showing some random values. ODO000003880 has 2 items and unit number is fetching Unit18 as value. 
4. ODO000003880 has two items I1 and Item1001. Item I1 is picked and Item1001 is not waved. Reason code against order should be multiple. Reason code against Item 1001 should be Not Waved.

thanks & regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
[Orders aged.zip](https://github.com/astpl1998/logistics/files/2627958/Orders.aged.zip)

**Comment by raju-kurup** [comment]
Development completed
