### ISSUE TITLE
10.Dvert -Daily Orders waved

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#19]
Dear Murugantham,

New Requirement for Dvert -Daily Orders waved
 Here with attached PFS for your Reference
PFB rtrack ID raised for Dvert MIS Report – Daily Orders Waved. This report also covers 2 other Reports,
Dvert_WMS_M0001	Daily Orders Waved
Dvert_WMS_M0011	Date and Time of last wave today
Dvert_WMS_M0013	Weekly Orders Waved

rTrack ID: EPE-6817

[10.Dvert_WMS_M0001_Daily Orders Waved_V1 1 3-5-2018.xlsx](https://github.com/murugananthaml/logistics/files/1969689/10.Dvert_WMS_M0001_Daily.Orders.Waved_V1.1.3-5-2018.xlsx)

Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
Dear Murugeshkumar
Ramco has some changes is happen in PFS .So Modification PFS Use this. Herewith attached for you Reference.
[10. Dvert_WMS_M0001_Daily Orders Waved_V1 1 as on 4-5-2018.xlsx](https://github.com/murugananthaml/logistics/files/1973295/10.Dvert_WMS_M0001_Daily.Orders.Waved_V1.1.as.on.4-5-2018.xlsx)
Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
Dear  Murugesh kumar,
Kindly update the PFS .herewith attached for your reference
[Uploading 10.Dvert_WMS_M0001_Daily Orders Waved_V1 1 as 4-5-2018.xlsx…]()an

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
Dear Murugeshkumar,
kindly refer the PFS. Herewith attached for your Reference
[10.Dvert_WMS_M0001_Daily Orders Waved_V1 1 as 4-5-2018.xlsx](https://github.com/murugananthaml/logistics/files/1994651/10.Dvert_WMS_M0001_Daily.Orders.Waved_V1.1.as.4-5-2018.xlsx)

Thanks & Regards,
Parthiban.R

**Comment by murugeshkumar-T** [comment]
Dear muruga, 
i have some new development work in yg 1 
kindly assign this report to any other developer.

**Comment by Ezhilarasi-SP** [comment]
Dear Parthiban,
I need data for these fields 7,9,13,14,16,18,19,22..
12 columns logic completed.

**Comment by Ezhilarasi-SP** [comment]
The following fields are not found in the development server
1)unit no (CubedTHU)
2)reason code (outbound screen)
3)LDP ID (CubedTHU)

Need clarification on ` the below columns
1)item status multine (Outbound   Order Screen/Wave/Pick/Pack/Dispatch/Load)
2)order status (need multiple ware orders with different status)
3)unit status (outbound order)

**Comment by parthiban25** [comment]
Dear Murugeshkumar,
Report Name: Daily Orders waved
pending Points logics are Given. Kindly completed the Report

Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
Dear Ezhilarasi,
 Report Name: Daily Orders waved
 pending Points logics are Given. Kindly completed the Report

Thanks & Regards
 parthiban.R

**Comment by Ezhilarasi-SP** [comment]
Dear Parthiban,
Report Name: daily orders waved
report mapped in uat.
latest stored procedure not yet compiled in uat server.

**Comment by parthiban25** [comment]
Dear Ezhil,
Daily order in Wave testing issues update as on 17_5_2018


[order waved report issues.xlsx](https://github.com/murugananthaml/logistics/files/2011797/order.waved.report.issues.xlsx)


Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
Dear Ezhil
kindly find the CubeTHU screen item code,qty, attached for screen shot
[CUbeTHu shot.xlsx](https://github.com/murugananthaml/logistics/files/2015941/CUbeTHu.shot.xlsx)

Thank You
Parthiban.R

**Comment by Ezhilarasi-SP** [comment]
Dear Parthiban,

so and wave details not available for outbound orders

**Comment by parthiban25** [comment]
Dear ezhil,
CubeTHU is Discuss with ramco given solution after then field added
while filter Date is given System throw error"proivde to date"

thanks & regards
parthiban.R

**Comment by Ezhilarasi-SP** [comment]
Dear Parthiban,
Kindly test the report in development server in adminuser .
report name: vert daily order waved.
kindly provide data for pick screen and cubedthu screen.

**Comment by Ezhilarasi-SP** [comment]
Dear Parthiban ,
Kindly test the report on development server.
report name: vert daily order waved

**Comment by Ezhilarasi-SP** [comment]
@murugananthaml
test

**Comment by Ezhilarasi-SP** [comment]
Dear Parthiban ,
Kindly test the report on development server.
report name: vert daily order waved

**Comment by nanda32** [comment]
Issues logged by ramco on 25-05-2018
1. Seller filter is defaulted with ALL but in the list ALL is unavailable., So when I chose another seller and if I again want to choose ALL option, I cannot do it so.
2. Location description and seller description is not fetching in filters grid upon choosing
3. In filter box, if Date_To is less than Date_From, on pressing OK, error have to be thrown on screen
4. Waved_Time only displays date and not time
5. Most of the fields fr order ODO000000001 is blank like item_id etc
6. For ODO ODO000003527, zone, LSP ID,  is not coming on UI
7. Unit status for ODO ODO000003527 is coming wrong on UI
8. Wave accuracy and User ID information is not coming.
9. Reason codes are not coming for some orders which are cancelled.

**Comment by nanda32** [comment]
everywhere the names of the fields are coming with ‘_’ sign in between words, e.g. Waved_Time, etc. Please fetch proper name of the fields.

**Comment by nanda32** [comment]
Issue logged on 28-05-2018
1. Seller filter is defaulted with ALL but in the list ALL is unavailable., So when I chose another seller and if I again want to choose ALL option, I cannot do it so.
2. Location description and seller description is not fetching in filters grid upon choosing
3. In filter box, if Date_To is less than Date_From, on pressing OK, error have to be thrown on screen
4. Waved_Time only displays date and not time
5. Most of the fields fr order ODO000000001 is blank like item_id etc
6. For ODO ODO000003527, zone, LSP ID,  is not coming on UI
7. Unit status for ODO ODO000003527 is coming wrong on UI
8. Wave accuracy and User ID information is not coming.
9. Reason codes are not coming for some orders which are cancelled.

**Comment by Ezhilarasi-SP** [comment]
Hi Parthiban, 
  I have completed the issues (1,2,3,4,7)  in development server.
2) for the issues 5 fr order ODO000000001 there is no data in cubedth screen.
3) For ODO ODO000003527, zone, LSP ID,  is not coming on UI ( is not available in screen )
4) Reason codes are not coming for some orders which are cancelled   (is not available in screen)

**Comment by Ezhilarasi-SP** [comment]
hi parthiban,
 kindly check wave accuracy in vert development server

**Comment by parthiban25** [comment]
hi,
Testing issues by Ramco .Kindly resolve the issue
1. Some wave details are not getting fetched. Eg WAVE000000259. 
2. In search filter, options waved and draft is coming and at line level, confirmed and draft is coming, It should either be waved or confirmed to maintain homogeneity. 

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
Daily order in wave
Testing is completed regards
 2 Points .kindly move to UAT Server

Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
@Ezhil:kindly change title: Daily order Waved, ( reason code-->report as Blank ).UAT server

Thanks & regards
parthiban.R

**Comment by Ezhilarasi-SP** [comment]
Hi Parthiban,
The above mentioned changes has been completed, for changing the title name latest deiverables has to be deploy in uat.
i had raised mail to daya to deploy the latest delivarbles in uat.

**Comment by parthiban25** [comment]
hi Ezhil,
Ramco has been raised the issue as on 28-6-2018
1.Waved Time format should be in US format. 
2.Total orders against WAVE000000429 is showing wrong. Only one order is showing up on screen but in report total orders field is populating 9. 
3.In search filter Status is launching as Waved. But in the dropdown there is no status as waved 
4. Order Status is coming as blank against WAVE000000429 
5.WAVE000000443 and Outbound Order Number ODO000003873, carton loaded out is 000001558. Report is also showing carton number 000001554 as loaded which is not available in the loading execution

thanks & Regards
parthiban.R

**Comment by Ezhilarasi-SP** [comment]
Hi Parthiban,
          As i am working on curatio reports,Kindly allocate this issue to either Murugesh or devi.

**Comment by murugeshkumar-T** [comment]
[Daily Orders Waved.zip](https://github.com/astpl1998/logistics/files/2627939/Daily.Orders.Waved.zip)

**Comment by raju-kurup** [comment]
Development completed
