### ISSUE TITLE
11.Dvert-Orders in Queue

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#20]
Dear murugantham ,
Kindly assign the New Report-Dvert-Orders in Queue
Herewith attached for reference
[11.Dvert_WMS_M0006_Orders in Queue_V1 0 as 4-5-2018.xlsx](https://github.com/murugananthaml/logistics/files/1974687/11.Dvert_WMS_M0006_Orders.in.Queue_V1.0.as.4-5-2018.xlsx)
Thanks & regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
Dear parthiban, 
orders in queue report is inprogress 
need multiline data for cubing box details

**Comment by parthiban25** [comment]
Dear Murugeshkumar,
Report Name: Dvert-Orders in Queue
pending Points logics are Given. Kindly completed the Report

Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
Ramco issue Logged.Kindly resolve the issue

1. On launch of report, error is coming to provide from and to date. Date should be defaulted like other reports. 
2. When the status is chosen as fresh, confirmed orders are also getting fetched, ODO ODO000003750. Total of 579 orders are getting fetched. 
3. Status is not fetching appropriate outbound orders. 
4. Drill down is not happening if we click on "+" for carton. Check the attached pic. 
5. Outbound Order ODO000003612 status is showing as fresh. Carton status is loaded but reason code says replenishment needed. (Refer attachment – Capture)

Thanks & Regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
dear parthiban,
above mentioned first four issues are resolved 
point no 5 need clarification

**Comment by parthiban25** [comment]
hi,
Orders in Queue 
UAT server problem
VDT-365
VDT-290 (Point No 4 & 5 -Fix Reject)

Thanks & Regards
parthiban.R

**Comment by murugeshkumar-T** [comment]
Hi,
point no 4 & 5 will check with ramco and resolve by tomorrow 

Regards,
Murugeshkumar.T

**Comment by murugeshkumar-T** [comment]
@parthiban orders in queue report above mentioned issue is resolved in development server.

**Comment by parthiban25** [comment]
hi,
- VDT-429 again issue raised by ramco  29-6-2018
1. Filter shows Location Description as test on launch of report. 
2. Date From and Date To should be in US format. 
3. For Selection 6/1/2018 to 6/28/2018 total number of orders is coming as 210 but after removing duplicate values number is coming as 201. 
4. Carton No shows a total column which is irrelevant in this report 
5. ODO000003824 is showing in confirmed status in the report even though the order is packed. 
6. Cartons with loaded status are coming in this report. 000001558, 000001192 and 000001193

thanks & regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
[Orders in Queue.zip](https://github.com/astpl1998/logistics/files/2627965/Orders.in.Queue.zip)

**Comment by raju-kurup** [comment]
Development completed
