### ISSUE TITLE
13.Dvert-Inventory Exceptions Alert

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#22]
Dear murugantham,
kindly refer attached the New requirement for Inventory Exceptions Alert
[12.ANWMS031_Inventory_Exceptions Alert.docx](https://github.com/murugananthaml/logistics/files/1983281/12.ANWMS031_Inventory_Exceptions.Alert.docx)
Thanks & Regards
Paarthiban.R

**Comment by Jeyapriyat** [comment]
dw design completed ,kindly load the data's for pick screen

**Comment by Jeyapriyat** [comment]
need sample data for pick screen.

**Comment by parthiban25** [comment]
Dear Jeyapriya
Inventory Exceptions Sample Data update in Development server
http://172.16.18.58/RVW/extui/vwrt/LaunchPanel.htm
ramcouser
ramco123$$
[inventory Exceptions.xlsx](https://github.com/murugananthaml/logistics/files/2012423/inventory.Exceptions.xlsx)

Thanks & Regards
Parthiban.R

**Comment by Jeyapriyat** [comment]
Dear Parthiban
Report completd,kindly check and revert ne back.
regards,
jeyapriya

**Comment by parthiban25** [comment]
Dear murugantham,
Kindly resolved this issues  Inventory Exception Alert not triggered for short closed Pick Plan PICKPLN000000361

Thanks & regards
parthiban.R

**Comment by murugananthaml** [comment]
unit test completed mail has come

**Comment by parthiban25** [comment]
Dear Murugantham,
alert working fine 
But In Excel -->Reason code have been came as Empty. kindly resolved the issues

Thanks & Regards
parthiban.R

**Comment by murugananthaml** [comment]
reason code issue resolved . please check

**Comment by murugananthaml** [comment]
rtrack id VDT-360

**Comment by raju-kurup** [comment]
Development completed
