### ISSUE TITLE
14.Dvert-Cycle count variance alert

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#23]
Dear murugantham,
kindly refer attached the New requirement for cycle count Variance alert
[14.ANWMS035_Dvert_CycleCountVariance.docx](https://github.com/murugananthaml/logistics/files/1983288/14.ANWMS035_Dvert_CycleCountVariance.docx)

Thanks & Regards
parthiban.R

**Comment by Jeyapriyat** [comment]
dw design completed,kindly load the datas for Stock Accuracy

**Comment by Jeyapriyat** [comment]
report sp completed.

**Comment by Jeyapriyat** [comment]
Dear Parthiban
report email attachement finished,trigger logic need to write.
Regards,
jeyapriya

**Comment by DeviAmitysoft** [comment]
I have completed 1st level,Kindly check and revert.

**Comment by parthiban25** [comment]
hi Devi

Execution plan no : SAEXEPLN000000011,accuracy plan no:SAPLN000000006

thanks & regards
parthiban.R

**Comment by murugeshkumar-T** [comment]
[RAMCO CYCLE COUNT VARIANCR.zip](https://github.com/astpl1998/logistics/files/2627970/RAMCO.CYCLE.COUNT.VARIANCR.zip)

**Comment by raju-kurup** [comment]
Development completed
