### ISSUE TITLE
15.DVert-Task Aging trigger

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#24]
Dear murugantham,
Kindly refer the New E-mail Trigger for Dvert _Task Aging Trigger

[15.ANWMS047_Task_Aging.docx](https://github.com/murugananthaml/logistics/files/1987484/15.ANWMS047_Task_Aging.docx)

Thanks & regards
parthiban.R

**Comment by Jeyapriyat** [comment]
screen details needed

**Comment by Jeyapriyat** [comment]
screen details need.

**Comment by murugananthaml** [comment]
@murugeshkumar-T 
report name : vert_task_aging in development server . please start sp design completed

**Comment by murugeshkumar-T** [comment]
Dear Parthiban,
Task aging trigger is completed in vert development server kindly check,
if have any modifications kindly let me know

**Comment by parthiban25** [comment]
hi,
Task Aging Trigger
1.PICK PLAN NO:PICKPLN000000347 status as changed Assigned it revised
2.pack plan no:PACKPLN000000187,PACKPLN000000186 status changed as Assigned it revised
3.loading:DISPATCH000000092 status as Ready For Transfer
4.unloading :ULPLN000000038 status as assingned
5.putaway:PUTPLN000000200 status as assigned
thanks & Regards
Parthiban.R

**Comment by Jeyapriyat** [comment]
issue completed.kindly check and revert.

**Comment by parthiban25** [comment]
hi,
Development server testing issues as on 27-6-2018
Task aging 
loading mail received but Excel paln number is truncted

thanks & regards
parthiban.R

**Comment by murugeshkumar-T** [comment]
[RAMCO TASK AGING.zip](https://github.com/astpl1998/logistics/files/2628004/RAMCO.TASK.AGING.zip)

**Comment by raju-kurup** [comment]
Development completed
