### ISSUE TITLE
16.Dvert-Skips in Picking trigger

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#25]
Dear murugantham,
Kindly refer the New E-mail Trigger for Dvert _Skips in Picking trigger

[16.ANWMS049_Skips_in_Picking.docx](https://github.com/murugananthaml/logistics/files/1987490/16.ANWMS049_Skips_in_Picking.docx)

Thanks & regards
parthiban.R

**Comment by Jeyapriyat** [comment]
dw report design completed.

**Comment by Jeyapriyat** [comment]
report sp completed.schedule sp need to write.

**Comment by murugananthaml** [comment]
completed

**Comment by Ezhilarasi-SP** [comment]
I have completed 1st level Skips in Picking trigger.

**Comment by murugeshkumar-T** [comment]
[RAMCO SKIPS AND PICKING.zip](https://github.com/astpl1998/logistics/files/2628001/RAMCO.SKIPS.AND.PICKING.zip)

**Comment by raju-kurup** [comment]
Development completed
