### ISSUE TITLE
17.Dvert-Released Orders Per Zone trigger

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#26]
Dear murugantham,
 Kindly refer the New E-mail Trigger for Dvert _Skips in Released Orders Per Zone

[17.ANWMS050_Released_Orders_Per_Zone.docx](https://github.com/murugananthaml/logistics/files/1987502/17.ANWMS050_Released_Orders_Per_Zone.docx)
Thanks & regards
 parthiban.R

**Comment by Jeyapriyat** [comment]
dw design completed.

**Comment by murugananthaml** [comment]
6.Inventory Availability column pending

**Comment by murugeshkumar-T** [comment]
[RAMCO RELEASER ORDER PER ZONE.zip](https://github.com/astpl1998/logistics/files/2627996/RAMCO.RELEASER.ORDER.PER.ZONE.zip)

**Comment by raju-kurup** [comment]
Development completed
