### ISSUE TITLE
18.Dvert-Average Warehouse Capacity Report 

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#27]
Dear Murugantham
New Report Ramco Assign as on 18-5-2018 .Delivery Date:24-5-2018.
Report Type:  ARI
Report Name :   Average Warehouse Capacity Report 
Rtack id:   EPE-7032
customer name:Dvert
[12.Dvert_WMS_M0016_Average_Warehouse Capacity Report_V1.0 as on 18-5-2018.xlsx](https://github.com/murugananthaml/logistics/files/2015688/12.Dvert_WMS_M0016_Average_Warehouse.Capacity.Report_V1.0.as.on.18-5-2018.xlsx)

Thanks & Regards
Parthiban.R

**Comment by DeviAmitysoft** [comment]
Dear Parthiban,
                    I have completed Report,Kindly check and revert.report name : 
Average Warehouse Capacity used

**Comment by parthiban25** [comment]
hi Devi
Average warehouse capacity used-->Testing is completed -->changes center alignment, location display one time, average warehouse used one display: after that move to UAT server

Thanks & regards
parthiban.R

**Comment by DeviAmitysoft** [comment]
Dear Parthiban,
                I have completed the report,Kindly check and revert.

**Comment by DeviAmitysoft** [comment]
@parthiban25 
Kindly Provide test data for the mentioned issue.

**Comment by DeviAmitysoft** [comment]
@parthiban25 
Mentioned currections are completed in development server,Kindly check and revert.

**Comment by parthiban25** [comment]
hi Devi,
'1. Bin details are duplicating in the report. 
2. Utilization is showing 0 value. 
3. Average Warehouse Capacity should consider all the bins in the warehouse for the report issue logged date 27-6-2018

Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
hi Devi,
testing issues Average Capacity used
1	location ,zone,aisle,bins,capacity ,average warehouse capacity	this field should have been blanks.
2	Generated by location 	this field should have been blanks.
	kindly resolve the issue	
[average warehouse capacity used Defect.xlsx](https://github.com/murugananthaml/logistics/files/2143887/average.warehouse.capacity.used.Defect.xlsx)
Thanks &regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
[Average warehouse capacity used.zip](https://github.com/astpl1998/logistics/files/2627934/Average.warehouse.capacity.used.zip)

**Comment by raju-kurup** [comment]
Development completed
