### ISSUE TITLE
19.Dvert-Dock to stock report

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#28]
Dear murugantham,
Ramco have been assigning the New Report .After finishing the previous report kindly assign the Report
Report type : ARI
Report Name:Dock to stock report
Kindly refer the Attchement
[19.Dvert_WMS_M0022_Dock to Stock_V1 1 as 22-5-2018.xlsx](https://github.com/murugananthaml/logistics/files/2025912/19.Dvert_WMS_M0022_Dock.to.Stock_V1.1.as.22-5-2018.xlsx)

Thanks & Regards
Parthiban.R

**Comment by murugananthaml** [comment]
@DeviAmitysoft

**Comment by murugananthaml** [comment]
@DeviAmitysoft please do the design of this report

**Comment by DeviAmitysoft** [comment]
@murugananthaml  I have completed the design of this report

**Comment by murugananthaml** [comment]
@Jeyapriyat please write the backend logic

**Comment by Jeyapriyat** [comment]
report design and logic completed.need to add input parameter.

**Comment by parthiban25** [comment]
hi,
Dock to stock testing is completed kindly move to Vert UAT Server

Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
kindly changed the title: "Dock to Stock " align as center
Report launched throw error .kindly resolved the issue

Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
Dock to stock report 
Deployed in UAT server report  is launching  but fetching Header field wrongly .Kindly update the status

Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi Jeyapriya,
Ramco issued logged as on 27-6-2018
1. In filters total time taken for dock to stock is getting overlapped on the filter. 
2. Spelling of greater than and less than is wrong in the filter.
Rtack no:
1.VDT344
2.VDT421

thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi 
Ramco has been issuing logged as on 29-6-2018
1.In dock to stock report, ASN ASN000000235 is coming for which putaway is not in completed. 
2.spelling mistake for Greater( then modified as than)
Screenshot below. Defect logged – VDT-439
[Dock to stock.docx](https://github.com/murugananthaml/logistics/files/2151452/Dock.to.stock.docx)

Thanks & Regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
[Dock -to- Stock.zip](https://github.com/astpl1998/logistics/files/2627945/Dock.-to-.Stock.zip)

**Comment by raju-kurup** [comment]
Development completed
