### ISSUE TITLE
20.Lines Received and Putaway Per Person Per Hour

### ISSUE THREAD

**Issue by nanda32** [astpl1998/logistics#29]
[Dvert_WMS_M0015_Lines Received and Putaway per Person_V1 0-25-05-2018.xlsx](https://github.com/murugananthaml/logistics/files/2041316/Dvert_WMS_M0015_Lines.Received.and.Putaway.per.Person_V1.0-25-05-2018.xlsx)
Report assigned date by ramco:25-05-2018

**Comment by DeviAmitysoft** [comment]
Design Completed ,coding is in progress

**Comment by DeviAmitysoft** [comment]
Dear Parthiban,
                     for lpn no column need data .other columns are completed .

**Comment by DeviAmitysoft** [comment]
Dear Parthiban,
                  I have completed the report,Kindly check and revert.

**Comment by parthiban25** [comment]
hi,
kindly resolve the issue
[Lines receive01.xlsx](https://github.com/murugananthaml/logistics/files/2096937/Lines.receive01.xlsx)

Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
Hi
average LPNs person ,units in negative 
.kindly resolve the issue

**Comment by parthiban25** [comment]
hi,
Lines received and putaway per persons per lines report
putaway filter location,employees,operation,-->all are repeated one time display .total LPNs per hours ,-->alla data puts as zeros came,LPN Details -->it blank .kindly resolve the issues


[lines0007.xlsx](https://github.com/murugananthaml/logistics/files/2129713/lines0007.xlsx)

thanks & regards
parthiban.R

**Comment by DeviAmitysoft** [comment]
Dear Parthiban,
                   issue resolved,Kindly check and revert.

**Comment by DeviAmitysoft** [comment]
@parthiban25                 
Kindly Provide test data for the mentioned issue

**Comment by parthiban25** [comment]
hi,
Ramco has been raised issued 27-6-2018
1. Location description is loading with Test on launch. 
2. All option for employee is missing. 
3. Option to see both goods receipt and putaway operation is missing. 
4. Blank details are coming in LPN column even though 1 LPN has 1 item in the goods receipt.

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
Ramco has been raised issue as on 27-6-2018
1. Bin details are duplicating in the report. 
2. Utilization is showing 0 value. 
3. Average Warehouse Capacity should consider all the bins in the warehouse for the report

Thanks & regards
parthiban.R

**Comment by murugeshkumar-T** [comment]
[Lines received and putaway per person hour.zip](https://github.com/astpl1998/logistics/files/2627952/Lines.received.and.putaway.per.person.hour.zip)

**Comment by raju-kurup** [comment]
Development completed
