### ISSUE TITLE
21.Lines Picked Per Person Per Hour

### ISSUE THREAD

**Issue by nanda32** [astpl1998/logistics#30]
[Dvert_WMS_M0014_Line Picked Per Person Per Hour_V1 0-25-05-2018.xlsx](https://github.com/murugananthaml/logistics/files/2041320/Dvert_WMS_M0014_Line.Picked.Per.Person.Per.Hour_V1.0-25-05-2018.xlsx)
Report assigned date by ramco: 25-05-2018

**Comment by murugananthaml** [comment]
@Ezhilarasi-SP

**Comment by Ezhilarasi-SP** [comment]
design completed,
coding started .

**Comment by Ezhilarasi-SP** [comment]
development completed in development server, kindy test it.

**Comment by nanda32** [comment]
[lines picked per person per hour.xlsx](https://github.com/murugananthaml/logistics/files/2096939/lines.picked.per.person.per.hour.xlsx)
Employee code:0218
from date:08-06-2018 to date:08-06-2018
Data is not coming.

**Comment by Ezhilarasi-SP** [comment]
Hi Parthiban,
Kindly Provide test data for this report

**Comment by parthiban25** [comment]
hi,
Ramco has been raised issues as on 27-6-2018
1. Lines are getting duplicated against a single employee. 
2. Gave the date filter as 25th June but no data comes up in the report even though there are pick execution done on 25th June. 
thanks & regards
parthiban.R

**Comment by Ezhilarasi-SP** [comment]
Hi Parthiban,
Issues of VDT- 410  fixed, kindly test it in development server.

**Comment by Ezhilarasi-SP** [comment]
Hi Parthiban,
Issues of VDT- 410 fixed, kindly test it in development server.

**Comment by parthiban25** [comment]
hi Ezhil,
"1. Lines are getting duplicated against a single employee. 
2. Gave the date filter as 25th June but no data comes up in the report even though there are pick execution done on 25th June.
Issue logged as on 27-6-2018 
"
thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi ezhil
testing issues
1	filter option Location Id,Date From ,Date To	This field should have been Blank Required as Blank
		
2	Location 	Duplicate came one time Display is enough

[lines pick1.xlsx](https://github.com/murugananthaml/logistics/files/2143953/lines.pick1.xlsx)

Thanks & regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
[Lines Picked per person hour.zip](https://github.com/astpl1998/logistics/files/2627948/Lines.Picked.per.person.hour.zip)

**Comment by raju-kurup** [comment]
Development completed
