### ISSUE TITLE
Testing issues raised By Ramco

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#31]
Dear Murugantham,

Ramco has been raising the testing issues below mentioned excel before the completion as on 30th may 2018.kindly update the status 

[testing issues raised by ramco.xlsx](https://github.com/murugananthaml/logistics/files/2047931/testing.issues.raised.by.ramco.xlsx)

Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
Dear murugantham,
-Ramco has been raising the testing issues below mentioned excel as on 7-6-2018

[ramco testing issues as on 7-6-2018.xlsx](https://github.com/murugananthaml/logistics/files/2080374/ramco.testing.issues.as.on.7-6-2018.xlsx)

Thanks & Regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
dear parthiban, 
above mentioned issues are resolved  

Regards,
Murugeshkumar.T

**Comment by parthiban25** [comment]
hi 
Ramco should have been raising the Rrack status update the Report
[31.amity-Report Tracker-3-7-2018.xlsx](https://github.com/murugananthaml/logistics/files/2157896/31.amity-Report.Tracker-3-7-2018.xlsx)


Thanks &regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
Hi,

i have updated the rtrack status in attached excel.
kindly find the attached sheet.

**Comment by raju-kurup** [comment]
Development completed
