### ISSUE TITLE
new work1

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/logistics#39]

**Comment by murugananthaml** [comment]
![dw schedule](https://user-images.githubusercontent.com/37649615/42087997-95012ce0-7bb5-11e8-90c2-3c71c93b1e37.png)

**Comment by murugananthaml** [comment]
[trigger transaction testing.xlsx](https://github.com/murugananthaml/logistics/files/2148975/trigger.transaction.testing.xlsx)

**Comment by murugananthaml** [comment]
@Ezhilarasi-SP

**Comment by murugananthaml** [comment]
please do the needful

**Comment by astpl1998** [comment]
Used for Demo
