### ISSUE TITLE
1. Alert to Operations team on confirmation of BR(CKB)

### ISSUE THREAD

**Issue by Aamirsaad** [astpl1998/logistics#43]
Hi Team,

Please refer to the attach doc for more detail
[List of 13 Alerts Final (002).docx](https://github.com/murugananthaml/logistics/files/2169964/List.of.13.Alerts.Final.002.docx)

**Comment by parthiban25** [comment]
hi  Devi

pls find the attached the Test case and PFS
[1.Test case CKB 1st alert.docx](https://github.com/astpl1998/logistics/files/2273806/1.Test.case.CKB.1st.alert.docx)
[1.CKB-TMS-ALERT-01  Alert to Operations team on confirmation of BR.docx](https://github.com/astpl1998/logistics/files/2273807/1.CKB-TMS-ALERT-01.Alert.to.Operations.team.on.confirmation.of.BR.docx)

thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
hi devi
alert 1 :while click to save and confirm system throw error
Cameron server 

[alert01.xlsx](https://github.com/astpl1998/logistics/files/2313037/alert01.xlsx)
 thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
completed

**Comment by parthiban25** [comment]
Alert 1: completed
Alert to Operations team on confirmation of BR to 1. Alert to Operations team on confirmation of BR

**Comment by parthiban25** [comment]
hi,
latest sp Deployed in  AT server
ALERT-01 : Alert to Operations team on confirmation of BR

[CKB_BR_CONFIRMATION_TRIGGER.zip](https://github.com/astpl1998/logistics/files/2608130/CKB_BR_CONFIRMATION_TRIGGER.zip)

Thanks & regards
Parthiban.R

**Comment by raju-kurup** [comment]
Development completed
