### ISSUE TITLE
4. Alert should be sent to station manager informing of booking cancellation(CKB)

### ISSUE THREAD

**Issue by Aamirsaad** [astpl1998/logistics#46]
Hi Team,

Please refer to the attach doc for more detail
[List of 13 Alerts Final (002).docx](https://github.com/murugananthaml/logistics/files/2170246/List.of.13.Alerts.Final.002.docx)

**Comment by parthiban25** [comment]
hi Devi,
while click the short close attend time two alert came .kindly check the alert 4 &5

thanks & regards 
parthiban.R

**Comment by parthiban25** [comment]
alert 4:completed
 4. Alert should be sent to station manager informing of booking cancellation(CKB)

**Comment by parthiban25** [comment]
hi,
latest sp Deployed in  AT server
ALERT-04 : Alert should be sent to station manager informing of booking cancellation

[CKB_BR_CONFIRMATION_cancel_TRIGGER.zip](https://github.com/astpl1998/logistics/files/2608127/CKB_BR_CONFIRMATION_cancel_TRIGGER.zip)

thanks & regards
Parthiban.R

**Comment by raju-kurup** [comment]
Development Completed
