### ISSUE TITLE
5.Notification to driver that a BR pickup is cancelled.(CKB)

### ISSUE THREAD

**Issue by Aamirsaad** [astpl1998/logistics#47]
Hi Team,

Please refer to the attach doc
[List of 13 Alerts Final (002).docx](https://github.com/murugananthaml/logistics/files/2170255/List.of.13.Alerts.Final.002.docx)
 for more detail

**Comment by parthiban25** [comment]
alert 5:completed
 5.Notification to driver that a BR pickup is cancelled.(CKB)

**Comment by parthiban25** [comment]
hi,

latest sp Deployed in AT server

ALERT-05 : Notification to be sent to a driver on assigning a new booking

[CKB_BR_plan_short_closed_TRIGGER.zip](https://github.com/astpl1998/logistics/files/2608138/CKB_BR_plan_short_closed_TRIGGER.zip)

Thanks & Regards
parthiban.R

**Comment by raju-kurup** [comment]
Development completed
