### ISSUE TITLE
6. Alert to be sent to commercial team and warehouse manager informing on estimated arrival time (if to location of a trip is warehouse)(CKB)

### ISSUE THREAD

**Issue by Aamirsaad** [astpl1998/logistics#48]
Hi Team,

Please refer to the attach doc for more detail
[List of 13 Alerts Final (002).docx](https://github.com/murugananthaml/logistics/files/2170262/List.of.13.Alerts.Final.002.docx)

**Comment by parthiban25** [comment]
hi ezhil,
pls find the attached alert 6
[6(a).Test case CKB 6th alert.docx](https://github.com/astpl1998/logistics/files/2301438/6.a.Test.case.CKB.6th.alert.docx)
[6.CKB-TMS-ALERT-06  Alert to be sent to commercial team and warehouse manager informing on estimated arrival time (if to location of a trip is warehouse) (Autosaved).docx](https://github.com/astpl1998/logistics/files/2301439/6.CKB-TMS-ALERT-06.Alert.to.be.sent.to.commercial.team.and.warehouse.manager.informing.on.estimated.arrival.time.if.to.location.of.a.trip.is.warehouse.Autosaved.docx)
thanks & regards
parthiban.R

**Comment by Ezhilarasi-SP** [comment]
Hi Parthiban,
                   Completed this trigger and I need one transaction with confirm status.

**Comment by Ezhilarasi-SP** [comment]
Hi Parthiban,
Completed this trigger kindly check it.

**Comment by parthiban25** [comment]
hi ezhil

send the sp Backend object

**Comment by Ezhilarasi-SP** [comment]
Hi Parthiban,
Completed this trigger kindly check it .
[CKB_TMS_ALERT_TRIGGER .txt](https://github.com/astpl1998/logistics/files/2369665/CKB_TMS_ALERT_TRIGGER.txt)

**Comment by Ezhilarasi-SP** [comment]
HI Parthiban,
New changes has been completed, kindly check it

**Comment by Ezhilarasi-SP** [comment]
Hi Parthiban,
                     Please find an attachment of the alert 6.
[CKB_TMS_ALERT_TRIGGER_R.txt](https://github.com/astpl1998/logistics/files/2405243/CKB_TMS_ALERT_TRIGGER_R.txt)

**Comment by parthiban25** [comment]
hi,

Latest Sp Deployed in AT server

ALERT-07 : Alert to be sent to commercial team and warehouse manager informing on estimated arrival time (if to location of a trip is warehouse)

[CKB_TMS_ALERT_TRIGGER.zip](https://github.com/astpl1998/logistics/files/2608200/CKB_TMS_ALERT_TRIGGER.zip)

Thanks & Regards
Parthiban.R

**Comment by raju-kurup** [comment]
Development completed
