### ISSUE TITLE
7. Ability to send an alert to the Commercial , operation and QHSE team on recording of incident(CKB)

### ISSUE THREAD

**Issue by Aamirsaad** [astpl1998/logistics#49]
Hi Team,

Please refer to the attach doc for more detail
[List of 13 Alerts Final (002).docx](https://github.com/murugananthaml/logistics/files/2170267/List.of.13.Alerts.Final.002.docx)

**Comment by parthiban25** [comment]
Hi Murugesh,

pls find the attached for alert 7
[7(a).Test case CKB 7th alert.docx](https://github.com/astpl1998/logistics/files/2301341/7.a.Test.case.CKB.7th.alert.docx)
[7.CKB-TMS-ALERT-07 Ability to send an alert to the Commercial , operation and QHSE team on recording of incident.docx](https://github.com/astpl1998/logistics/files/2301342/7.CKB-TMS-ALERT-07.Ability.to.send.an.alert.to.the.Commercial.operation.and.QHSE.team.on.recording.of.incident.docx)


Thanks & regards
parthiban.R

**Comment by murugeshkumar-T** [comment]
Hi,
Alert -7 is completd in camroon server and also moved to CKB development server.
kindly test the alert.
i have attached the latest trigger here

**Comment by parthiban25** [comment]
alert 7: completed
 Ability to send an alert to the Commercial , operation and QHSE team on recording of incident(CKB)

**Comment by parthiban25** [comment]
hi,

latest SP Deployed in AT server

ALERT-08 : Ability to send an alert to the Commercial , operation and QHSE team on recording of incident

[CKB_INCIDENT_CREATION_TRIGGER.zip](https://github.com/astpl1998/logistics/files/2608187/CKB_INCIDENT_CREATION_TRIGGER.zip)


Thanks & Regards
Parthiban.R

**Comment by raju-kurup** [comment]
Development completed
