### ISSUE TITLE
9. Alert to be sent to origin station of a CN if there is a damaged qty. updated in a consignment note.(CKB)

### ISSUE THREAD

**Issue by Aamirsaad** [astpl1998/logistics#51]
[List of 13 Alerts Final (002).docx](https://github.com/murugananthaml/logistics/files/2170277/List.of.13.Alerts.Final.002.docx)
Hi Team,

Please refer to the attach doc for more detail

**Comment by parthiban25** [comment]
hi Jeyapriya,
pls find the attached the alert 9
[9(a).Test Case CKB 9th alert.docx](https://github.com/astpl1998/logistics/files/2301476/9.a.Test.Case.CKB.9th.alert.docx)
[9. CKB-TMS-ALERT- 9 Alert to be sent to origin station of a CN if there is a damaged qty. updated in a consignment note..docx](https://github.com/astpl1998/logistics/files/2301477/9.CKB-TMS-ALERT-.9.Alert.to.be.sent.to.origin.station.of.a.CN.if.there.is.a.damaged.qty.updated.in.a.consignment.note.docx)

thanks & regards
parthiban.R

**Comment by Jeyapriyat** [comment]
@parthiban25 
kindly provide test data in damaged quantity for alter9

**Comment by Jeyapriyat** [comment]
@parthiban25  alert 9 completed

**Comment by Jeyapriyat** [comment]
i have attached alert 9 object.
[alter 9.txt](https://github.com/astpl1998/logistics/files/2369687/alter.9.txt)

**Comment by Jeyapriyat** [comment]
@parthiban25  alert 9 changes completed , kindly check it.

**Comment by Jeyapriyat** [comment]
@parthiban25  i have attached alert 9 object.
[alert9.txt](https://github.com/astpl1998/logistics/files/2419570/alert9.txt)

**Comment by Jeyapriyat** [comment]
@parthiban25 

 i have attached alert 9 object.
[alert 9.txt](https://github.com/astpl1998/logistics/files/2483079/alert.9.txt)

**Comment by parthiban25** [comment]
hi,

latest sp Deployed in AT server
ALERT-10 : Alert to be sent to origin station of a CN if there is a damaged qty. updated in a consignment note.

[CKB_CN_DAMAGED_QUANTITY_TRIGGER.zip](https://github.com/astpl1998/logistics/files/2608154/CKB_CN_DAMAGED_QUANTITY_TRIGGER.zip)


Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
hi,

latest sp deployed in AT server

ALERT-09 : Alert to be sent to origin station manager and commercial team on revenue protection creation for consignment note.

[CKB_CREATION_CONSIGNMENT_TRIGGER.zip](https://github.com/astpl1998/logistics/files/2608168/CKB_CREATION_CONSIGNMENT_TRIGGER.zip)


Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

latest SP Deployed inAT server
ALERT-10 : Alert to be sent to origin station of a CN if there is a damaged qty. updated in a consignment note.

[CKB_CN_DAMAGED_QUANTITY_TRIGGER.zip](https://github.com/astpl1998/logistics/files/2619910/CKB_CN_DAMAGED_QUANTITY_TRIGGER.zip)


Thanks & Regards
Parthiban.R

**Comment by raju-kurup** [comment]
Development completed
