### ISSUE TITLE
10. Ability to alert the Operation team to complete   the Operating Plan on Due Date -1 days.(CKB)

### ISSUE THREAD

**Issue by Aamirsaad** [astpl1998/logistics#52]
Hi Team,

Please refer to the attach doc for more detail
[List of 13 Alerts Final (002).docx](https://github.com/murugananthaml/logistics/files/2170283/List.of.13.Alerts.Final.002.docx)

**Comment by Jeyapriyat** [comment]
@parthiban25 
kindly provide test data for alert 10

**Comment by parthiban25** [comment]
hi Jeyapriya

kindly refer the Test Data for alert 10
[10(a).Test case CKB 10th alert.docx](https://github.com/astpl1998/logistics/files/2314145/10.a.Test.case.CKB.10th.alert.docx)
 thanks & regards
parthiban.R

**Comment by Jeyapriyat** [comment]
@parthiban25  alert 10 completed

**Comment by Jeyapriyat** [comment]
[alert 10.txt](https://github.com/astpl1998/logistics/files/2369683/alert.10.txt)

**Comment by Jeyapriyat** [comment]
@parthiban25  changes completed in alert 10, kindly check and revert.

**Comment by Jeyapriyat** [comment]
@parthiban25 

i have attached alert 10 object 
[alert 10.txt](https://github.com/astpl1998/logistics/files/2483086/alert.10.txt)

**Comment by parthiban25** [comment]
hi,

Latest SP Deployed In AT Server

This alert Scheduler base working  include 

[latest.zip](https://github.com/astpl1998/logistics/files/2608234/latest.zip)

Thanks & Regards
Parthiban.R

**Comment by raju-kurup** [comment]
Development completed
