### ISSUE TITLE
11. Alert to Operations team on New RFQ to create Operating Plan(CKB)

### ISSUE THREAD

**Issue by Aamirsaad** [astpl1998/logistics#53]
Hi Team,

Please refer to the attach doc for more detail
[List of 13 Alerts Final (002).docx](https://github.com/murugananthaml/logistics/files/2170287/List.of.13.Alerts.Final.002.docx)

**Comment by parthiban25** [comment]
hi Devi,
pls find the attached for Word sheet
Test case for alert 11

[11.(a).Test case CKB 11th alert.docx](https://github.com/astpl1998/logistics/files/2314203/11.a.Test.case.CKB.11th.alert.docx)

Thanks & regards
parthiban.R

**Comment by raju-kurup** [comment]
Development completed
