### ISSUE TITLE
12.Alert to Destination Station and Commercial on missing shipment(CKB)

### ISSUE THREAD

**Issue by Aamirsaad** [astpl1998/logistics#54]
Hi Team,

Please refer to the attach doc for more detail
[List of 13 Alerts Final (002).docx](https://github.com/murugananthaml/logistics/files/2170291/List.of.13.Alerts.Final.002.docx)

**Comment by parthiban25** [comment]
hi jeyapriya,
pls find the attached PFS

[12.CKB-TMS-ALERT-12 Alert to Destination Station and Commercial on missing shipment.docx](https://github.com/astpl1998/logistics/files/2318317/12.CKB-TMS-ALERT-12.Alert.to.Destination.Station.and.Commercial.on.missing.shipment.docx)
thanks& regards
parthiban.R

**Comment by Jeyapriyat** [comment]
@parthiban25  kindly provide test data for alert12

**Comment by parthiban25** [comment]
hi,
latest Sp Deployed In AT Server

ALERT-15 : Alert to Destination Station and Commercial on missing shipment

[ckb_DS_Commercial_miss_shipment.zip](https://github.com/astpl1998/logistics/files/2608179/ckb_DS_Commercial_miss_shipment.zip)


Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
latest Sp Deployed In AT Server
ALERT-15 : Alert to Destination Station and Commercial on missing shipment

[ckb_DS_Commercial_miss_shipment.zip](https://github.com/astpl1998/logistics/files/2619912/ckb_DS_Commercial_miss_shipment.zip)


Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
Rullaya Tahitu issues
s.33 this alert was came while clicked Create Trip Plan from Create Trip Plan screen. thi is wrong trigger.  You have been sent test alert in Dev, pls send me your test alert in AT also.

**Comment by parthiban25** [comment]
hi,
testing mail
![image](https://user-images.githubusercontent.com/37869674/52516647-c970d200-2c54-11e9-99d1-71fbae786987.png)

thanks & regards
parthiban.R

**Comment by raju-kurup** [comment]
Issue closed
