### ISSUE TITLE
DEV - 13. Alert to Operation and EXIM Team on SPPB Release(CKB)

### ISSUE THREAD

**Issue by Aamirsaad** [astpl1998/logistics#55]
Hi Team,

Please refer to the attach doc for more detail
[List of 13 Alerts Final (002).docx](https://github.com/murugananthaml/logistics/files/2170293/List.of.13.Alerts.Final.002.docx)

**Comment by parthiban25** [comment]
hi  Devi ,
pls find the attached PFS alert 13
[13.CKB-TMS-ALERT-13 Alert to Operation and EXIM Team on SPPB Release.docx](https://github.com/astpl1998/logistics/files/2318307/13.CKB-TMS-ALERT-13.Alert.to.Operation.and.EXIM.Team.on.SPPB.Release.docx)
thanks & regards
parthiban.R

**Comment by Jeyapriyat** [comment]
@parthiban25 

i have attached alert 13 object.
[alert 13.txt](https://github.com/astpl1998/logistics/files/2483090/alert.13.txt)

**Comment by parthiban25** [comment]
hi,
latest Sp Deployed in AT server

ALERT-16 : Alert to Operation and EXIM Team on SPPB Release

[ckb_sppb_release.zip](https://github.com/astpl1998/logistics/files/2608191/ckb_sppb_release.zip)



Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
latest Sp Deployed in AT server

ALERT-16 : Alert to Operation and EXIM Team on SPPB Release

[ckb_sppb_release.zip](https://github.com/astpl1998/logistics/files/2619917/ckb_sppb_release.zip)


Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
Rullaya Tahitu Issues logged
s.32,  I have test with this transaction but no alert come.

Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi  
issues raised by jeyapriya
SPPB release 
scheduler problem raised to ramco

                         thanks & regards
                          parthiban.R

**Comment by parthiban25** [comment]
New requirement (Scheduler is not working)
pending with ramco

**Comment by parthiban25** [comment]
issue in revenue protection screen ramco to be resolved then we have to do testing

**Comment by astpl1998** [comment]
DueDate:29-06-19
Remarks:excellent

**Comment by astpl1998** [comment]
DueDate:27-09-19
Remarks:good

**Comment by raju-kurup** [comment]
Logisitic development closed, so closing this ticket
