### ISSUE TITLE
DEV-Incoming skus with changes in Inner Pack Qty

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#59]
hi murugesh,
pls find the attached for Dvert Development

thanks & Regard
parthiban.R

**Comment by murugeshkumar-T** [comment]
[Dverte New ARI Object as on 31-10-2018.zip](https://github.com/astpl1998/logistics/files/2574900/Dverte.New.ARI.Object.as.on.31-10-2018.zip)

**Comment by murugeshkumar-T** [comment]
[incomming sku uat 27-11.zip](https://github.com/astpl1998/logistics/files/2619460/incomming.sku.uat.27-11.zip)

**Comment by parthiban25** [comment]
hi,

pls find the Test case for Income SKUs in UAT sever


Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
Ramco raised the issue as on 28-11-2018


1.       ASN   for which only putaway is done is coming. It is not fetching list of complete   ASNs for which GR is done but no putaway. Ex. - ASN000001366
--
2.         For ASN ASN000001394, which was executed today (on   28th Nov), I   gave the filter for today’s date and it said – No data found. Due to this I   cannot check for the damaged qty and un-scan able qty.
DEFECT ID – VEDE-168

Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
1st points
GR is done But Filter option Putaway only(check with PFS)
2nd points
Date filter not working

Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
Defect by customer:Not filter working from 11-1-2018 to 11-1-2018  :GRN GREXE000005229
filter option
GRN From & To Date status as complete
Putaway From & To Status as completed

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi ,
Testing  issues Devert: Income sku with changes inner pack qty
GR is working but Putaway not working filer from 11-1-2018 to 11-1-2018 
ASN000000367
ASN000000385
ASN000000386
ASN000000387
ASN000000388
ASN000000389
ASN000000390 

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi jeyapriya,

Report launching error,
Incoming SKUs with changes in inner pack qty ARI report launching error

refer Skype :3.44p.m 
26-12-2018

thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi jeyapriya,

navigation:logistics administration>wmactivity>goods receipts and select as all plans and primary ref.Doc also Empty then search as came shown list use this plan
plan no:GRPLN000000217
start date:12/07/2018 11:35:00 AM
end date:12/07/2018 11:35:33 AM
GR execution no:GREXE000006225


Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
Ramco raised the issue as on 28-11-2018
 1.       ASN for which only putaway is done is coming. It is not fetching list of complete ASNs for which GR is done but no putaway. Ex. - ASN000001366
2.       For ASN ASN000001394, which was executed today (on 28th Nov), I gave the filter for today’s date and it said – No data found. Due to this I cannot check for the damaged qty and un-scan able qty.
DEFECT ID – VEDE-168

Thanks & Regards
Parthiban.R

**Comment by Jeyapriyat** [comment]
@parthiban25 

i have attached the latest sp in incom sku report
[final incom sku 8-2-2019.zip](https://github.com/astpl1998/logistics/files/2844914/final.incom.sku.8-2-2019.zip)

**Comment by parthiban25** [comment]
Hi,

Issue has been Resolved 
Sp moved to UAT server 
Latest SP 8-2-2019
[VERT_INCOME_SKU_CHGIN_INNERPCKQTY_SP.zip](https://github.com/astpl1998/logistics/files/2844924/VERT_INCOME_SKU_CHGIN_INNERPCKQTY_SP.zip)


Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

In report GR Execution No field as came wrong
1.Navigation Logistics administration >wmactivity>GRN.
Execution click and refer.no as Empty the search icon click

it will come report 
[income skus.zip](https://github.com/astpl1998/logistics/files/2845066/income.skus.zip)

![image](https://user-images.githubusercontent.com/37869674/52478387-3dff2e80-2bcb-11e9-9cbb-d8d3b00207c0.png)
![image](https://user-images.githubusercontent.com/37869674/52478461-6dae3680-2bcb-11e9-9b04-fd61037b7a1b.png)

![image](https://user-images.githubusercontent.com/37869674/52478487-8585ba80-2bcb-11e9-9af6-9d7bf89859d2.png)

refer the screen shot
1.screen shot refer with Good Receipt with plan number without plan --->GRN execution no came in report
2.screen shot refer with putaway  with plan number without plan -->GRN Execuion in report based on ASN

Thanks & regards
Parthiban.R

**Comment by Jeyapriyat** [comment]
@parthiban25 

issue solved,kindly check and revert.

i have attached latest sp.
[new.zip](https://github.com/astpl1998/logistics/files/2845179/new.zip)

**Comment by parthiban25** [comment]
hi,
Report name:income skus with inner pack qty
Report Type:ARI
After correcting the  feedback given to Ramco as on 8-2-2019

Date filters are not working
Net Qty is coming as negative. That cannot be the case ever.
GR execution is fetching putaway execution number also
Actual putaway qty is coming as per plan and not as per item. Due to this entire calculation is going wrong.

Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
latest status for Income skus with inner pack qty
1.Net Qty is coming as negative. That cannot be the case ever

2.Actual putaway qty is coming as per plan and not as per item. Due to this entire calculation is going wrong

Thanks & regards
parthiban.R

**Comment by DeviAmitysoft** [comment]
Hi,
  Kindly find the attached deliverables.
[incomming sku uat 03-05-19.zip](https://github.com/astpl1998/logistics/files/3141797/incomming.sku.uat.03-05-19.zip)

**Comment by raju-kurup** [comment]
Logisitic development closed, so closing this ticket
