### ISSUE TITLE
DEV-Dverte -order Line Fill rate

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#60]
hi jeyapriya

pls find the New Development for Dverte alert

Thanks & regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
[ORDER LINE FILL RATE UAT.zip](https://github.com/astpl1998/logistics/files/2619451/ORDER.LINE.FILL.RATE.UAT.zip)

**Comment by parthiban25** [comment]
hi,

ramco raised the issues as on 28-11-2018


1.       All   the orders are not coming in the report like ODO000008533. Total 3854 orders   were available on the screen when the report was generated across multiple   status for date range 1st – 28th Nov
--
2.         Lines are getting duplicated for ODO ODO000006044
3.         For order ODO000004754, all the SKUs are not   visible. And also customer field is blank for the same.
4.         Also, can you please shed some light on the below   part of the rules. Where can I see the Order line fill rate?


Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

1st point
-->Date filter not working against  outbound order from & to Date (3845 confirmed+10cancelled+1closed=3865)shown the report
-->Duplicate for SKUs,Order,carton Id,carton status,status.Refer:
ODO000004671(filter 1st nov to 28 th nove 2018)
2st point
All lines are Duplicate for Report .
3th points
ODO000004754 for order 4 SKU but report 3 Only came.customer against skus will be populated
4th points
clarification need

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

filter check | 1 | Date filter irrespective of all status   against Outbound order |  
-- | -- | -- | --
location ID | 2 | irrespective of location also check location id |  
Outbound order Date | 3 | check the outbound order Date mm/dd/yyyy.not required as time (check the   Date filter) |  
Outbound order No | 4 | outbound order required not   Duplicate     Date filter checking,multiple scenario also check now |  
customer ID | 5 | Against outbound order item master against customer id Field populated |  
SKU | 6 | carton and outbound order  combination item fetch .suppose missing in   combination  means and take the   outbound order itemfetch
order Quantity | 7 | carton and outbound order  combination item qty fetch.suppose missing   in combination  means and take the   outbound order qty fetch
ODO Load Date | 8 | outbound order against Execution End Date |  
Carton ID | 9 | Carton ID against the SKU and   outbound order combination |  
Carton Status | 10 | carton status |  
Status | 11 | outbound order status |  

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
testing,
missing the outbound order

order fill rate filter from 11-5-2016 to 11-6-2018 report record shown confirmed 2942 but original record shown as 4150 .kindly check the excel missing order check

[order02.xlsx](https://github.com/astpl1998/logistics/files/2647562/order02.xlsx)


Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
testing
outbound order

order fill rate 

point 1:carton id ,carton status put as empty

point 2: i have check the report from 11-5-2018 to 11-6-2018 .original report confirmed 4150  but development report 3975 as conformed missing as 175 outbound order

Thanks & Regards
Parthiban.R


[order 04.xlsx](https://github.com/astpl1998/logistics/files/2648889/order.04.xlsx)
thanks & regards
Parthiban.R

**Comment by Jeyapriyat** [comment]
@parthiban25 

order line fill rete report completed, i have attached latest sp.

[](url)

**Comment by parthiban25** [comment]
hi,
Testing issues in Dvert -Order line fill rate ARI report
order quantity is missing for outbound order ODO000055371

Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
testing issues in Dvert -order line fill rate
order line fill rate :   outbound order , sku order qty ,carton id,carton status as wrong 
ODO000055240  ,  C1SKUA009 ,  3.00,     000123456700003618,   Suggested, this is correct
this is report status 
ODO000055240,  C1SKUB105,   1.00,  000123456700004788,   Loaded,  this  all are rreport launched wrongly
                              C1SKUA009
                               C1SKUA040

Thanks & regards
Parthiban.R

**Comment by Jeyapriyat** [comment]
@parthiban25 
latest object in order line fill rate.
[VERT_ORDER_LINE_FILL_RATE_1.txt](https://github.com/astpl1998/logistics/files/2678970/VERT_ORDER_LINE_FILL_RATE_1.txt)

``

**Comment by parthiban25** [comment]
hi jeyapriya,
order line fill rate issue
1.Customer ID
2.ODO Load Date	
3.Carton ID	
4.Carton Status
for 4 field put it as blank refer the SKYPE attachment

Skype:3.30p.m 26-12-2018

**Comment by Jeyapriyat** [comment]
@parthiban25 

order line fill rate completed,kindly check and revert.

**Comment by parthiban25** [comment]
hi,

order line fill rate 

issues has been resolved 

1.       All the orders are not coming in the report like ODO000008533. Total 3854 orders were available on the screen when the report was generated across multiple status for date range 1st – 28th Nov

2.       Lines are getting duplicated for ODO ODO000006044
 3.       For order ODO000004754, all the SKUs are not visible. And also customer field is blank for the same.
 4.       Also, can you please shed some light on the below part of the rules. Where can I see the Order line fill rate?
 VEDE-169
Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
Ramco Amol Raise the issues as on 9-1-2019

1.	Location description in the report is not coming correctly. It is fetching the default location description.
2.	ODO Load Date is defaulted as 2/27/2018 12:00:00 AM for all the orders.
3.	ODO date and load execution date is also showing time. It should only be date. Is this the requirement in the logic sheet? Please confirm.
4.	Orders with under-amendment and fresh status are also coming.
thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi Jeyapriya
Ramco Amol Raise the issues as on 9-1-2019
below mention the four points 2,3,4 resolved point 1 is pending
1.Location description in the report is not coming correctly. It is fetching the default location description.
2.ODO Load Date is defaulted as 2/27/2018 12:00:00 AM for all the orders.
3. ODO date and load execution date is also showing time. It should only be date. Is this the requirement in the logic sheet? Please confirm.
4. Orders with under-amendment and fresh status are also coming.

thanks & regards
parthiban.R

**Comment by Jeyapriyat** [comment]
@parthiban25 

i have attached latest sp in order line fill rate report
[final order 8-2-2019.zip](https://github.com/astpl1998/logistics/files/2844904/final.order.8-2-2019.zip)

**Comment by parthiban25** [comment]
hi ,
isssue has been resolved sp move to UAT server 
latest Sp 8-2-2019

[VERT_ORDER_LINE_FILL_RATE_1 (5).zip](https://github.com/astpl1998/logistics/files/2844916/VERT_ORDER_LINE_FILL_RATE_1.5.zip)
thanka & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
After correcting the  feedback given to Ramco as on 8-2-2019

At the time of report launching, location description is not getting defaulted and the same value (null) is passes in the report also. Location description should be fetched of the default location code.
For the order ODO000004441, mapped with carton 000002289, loading date is not getting fetched. This line is loaded against load execution LOADEXE000000277.
Filters are coming as Loc_desc; Date_from; etc.

Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
latest status of order line fill rate
issues
But Location Description not came in Excel sheet in progress
All the orders are not getting fetched for the date rangesolution to amity Already all ASN should be came you have to change the only closed ,confirmed status required  Where to apply filters? Couldn’t find any mail. (Attached in vert report status)  Ok understood and accepted my mistake. Was not sure of the logic provided. I request you to please fetch all the orders irrespective of their status as mentioned in the logic sheet. 

Thanks & Regards
Parthiban.R

**Comment by astpl1998** [comment]
DueDate:29-06-19
Remarks:good

**Comment by astpl1998** [comment]
DueDate:30-07-2019
Remarks:good

**Comment by astpl1998** [comment]
DueDate:<flask_table.columns.Col object at 0x00000164A0D209E8>
Remarks:<flask_table.columns.Col object at 0x00000164A0FA3B00>

**Comment by raju-kurup** [comment]
Logisitic development closed, so closing this ticket
