### ISSUE TITLE
DEV-DVerte -inventory Days  of supply

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#61]
hi murugesh,

pls start the New Development for Dvert
Remaining Details Send to mail
Thanks & regards
Parthiban.T

**Comment by murugeshkumar-T** [comment]
[inventry days of supply objects on 13-11-2018.zip](https://github.com/astpl1998/logistics/files/2574810/inventry.days.of.supply.objects.on.13-11-2018.zip)

**Comment by murugeshkumar-T** [comment]
[inventry days on supply uat 27-11.zip](https://github.com/astpl1998/logistics/files/2619445/inventry.days.on.supply.uat.27-11.zip)

**Comment by parthiban25** [comment]
hi,

pls find the attached PFS & Test case in UAT server

[3.1Dvert_WMS_M0026 - Inventory Days of Supply as on 16-11-2018.xlsx](https://github.com/astpl1998/logistics/files/2619954/3.1Dvert_WMS_M0026.-.Inventory.Days.of.Supply.as.on.16-11-2018.xlsx)


Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi ,
Ramco has been issued Logged as on 28-11-2018


Dispatch plan DISPATCH000000270,   DISPATCH000000274 was in ‘Ready for transfer’ status but it is still showing   up in the report.     DEFECT ID – VEDE-168



Thanks & Regards
Parthiban.R
--

**Comment by parthiban25** [comment]
hi,
Report name:inventory Days of supply
Report Type:ARI
After correcting the feedback given to Ramco as on 8-2-2019

Dates filter are not working. Filters applied from 1st Nov to current date
Location description is not fetching correctly in the report

Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
As we Discuss with Phone call regarding Inventory Days of Supply reports
Our Developed Sp Deliverable .pls refer the attached

Error also fixed then send to ramco 14-2-2019
[inventry days on supply uat 27-11.zip](https://github.com/astpl1998/logistics/files/2871644/inventry.days.on.supply.uat.27-11.zip)
Regards
Parthiban.R

**Comment by DeviAmitysoft** [comment]
[inventry days on supply uat 03-05-19.zip](https://github.com/astpl1998/logistics/files/3141762/inventry.days.on.supply.uat.03-05-19.zip)

**Comment by DeviAmitysoft** [comment]
Kindly find the attached deliverables

**Comment by astpl1998** [comment]
DueDate:29-06-19
Remarks:good

**Comment by raju-kurup** [comment]
Logisitic development closed, so closing this ticket
