### ISSUE TITLE
DEV-01.stock ledger

### ISSUE THREAD

**Issue by nanda32** [astpl1998/logistics#9]
[01. PC_WMS_MIS Report_0012_Stock Ledger_V 1 0.xlsx](https://github.com/astpl3/logistics/files/1855724/01.PC_WMS_MIS.Report_0012_Stock.Ledger_V.1.0.xlsx)

**Comment by nanda32** [comment]
Stores ledger testing issues:

1.While landing the stores ledger screen customer code and location should be defaulted.
2.Border is incomplete
3.Report generated by user is not fetching
4.As per the requirement given format should be in(PDF,XLSX/csv)
5.If report is generated in xlsx format border to be corrected.
6. If report is generated in xlsx format report generated by field is missing.
7.If date range is given below 30 days currently system opens another window and populate the issue.issue should be shown in the base screen itself.
[stores ledger testing -27-04-2018.pdf](https://github.com/murugananthaml/logistics/files/1954187/stores.ledger.testing.-27-04-2018.pdf)

**Comment by nanda32** [comment]
Stores ledger testing issues:
1.At the end of the report Report generated by =username(based on the login user system should fetch the employee name.

**Comment by murugananthaml** [comment]
as discussed please check username + given name is coming in the report

**Comment by parthiban25** [comment]
Dear Murugantham,
#9 points .Username +Given Name .Show Empty. Pls give the screen shot for product Launched report

Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
Dear Murugantham,
Kindly update the Username  came  but Given Name  Show Empty. Here attached screen shot for reference
[Stock ledger 2-5-2018.docx](https://github.com/murugananthaml/logistics/files/1965978/Stock.ledger.2-5-2018.docx)

Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
Dear murugantham,
Ramco testing issues against stock ledger,
PFB issue found in Stock Ledger Report. 
Sum of ATP Qty against an Item as on ‘Date To’(Search Criteria) should be equal to the Final Closing Balance in the Report against the Item
Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
Dear  Muruganatham,

Actual out qty is 100 .But system qty it will show 1000.kindly resolve the issue

[Stock_Ledger as on 29_05_2018.xlsx](https://github.com/murugananthaml/logistics/files/2048436/Stock_Ledger.as.on.29_05_2018.xlsx)

**Comment by parthiban25** [comment]
hi,
 
Stock ledger report .Kindly resolve the issue
[stock ledger01.xlsx](https://github.com/murugananthaml/logistics/files/2096951/stock.ledger01.xlsx)

Thanks & Regards
parthiban.R

**Comment by parthiban25** [comment]
hi ,
stock ledger modification has been done in Test server as on 23-11-2018

[stock ledger 01.xlsx](https://github.com/astpl1998/logistics/files/2619979/stock.ledger.01.xlsx)
[Uploading stock ledger.pdf…]()


thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

stock Ledger Report Deployed in Live server 
Front object and Backend object 
pls refer the attached
[STOCK LEDGER.zip](https://github.com/astpl1998/logistics/files/2620001/STOCK.LEDGER.zip)


thanks & regards
Parthiban.R

**Comment by raju-kurup** [comment]
Development completed
